CREATE TABLE `lin` (
   LossInjuryID int unsigned auto_increment not null,
   OrganizationID int,
   JobTitleID int,
   HrsPerDay float,
   DaysPerWeek float,
   EarningsCalculationMethodID int,
   EarningsStartDate date,
   EarningsEndDate date,
   LocalAvgDailyEarnings decimal(12,4),
   AvgDailyEarnings decimal(12,4),
   LocalAvgWeeklyEarnings decimal(12,4),
   AvgWeeklyEarnings decimal(12,4),
   LocalAvgMonthlyEarnings decimal(12,4),
   AvgMonthlyEarnings decimal(12,4),
   LocalAvgAnnualEarnings decimal(12,4),
   AvgAnnualEarnings decimal(12,4),
   EarningsAttached bool default 0,
   ShiftID int,
   TaskID int,
   InjuryTaskDesc text,
   InjuryExposureID int,
   InjuryExposureDesc text,
   InjurySource1ID int,
   InjurySource2ID int,
   InjurySourceDesc text,
   InjuryObject varchar(128),
   ObjectDesc text,
   RegulatoryRecordable bool default 0,
   PrivacyCase bool default 0,
   Rationale text,
   WorkBegan datetime,
   DateofDeath date,
   InjuryIllnessCategoryID int unsigned not null,
   InjuryIllnessTypeID int unsigned not null,
   PrimaryTreatingFacilityID int,
   EmergencyRoom bool default 0,
   Hospitalized bool default 0,
   RecorderJobTitleID int,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      LossInjuryID
   )
) TYPE=InnoDB;

-- statement separator --


CREATE TABLE `lin_l` (
   _RecordID int unsigned not null auto_increment,
   LossInjuryID int unsigned  not null,
   OrganizationID int,
   JobTitleID int,
   HrsPerDay float,
   DaysPerWeek float,
   EarningsCalculationMethodID int,
   EarningsStartDate date,
   EarningsEndDate date,
   LocalAvgDailyEarnings decimal(12,4),
   AvgDailyEarnings decimal(12,4),
   LocalAvgWeeklyEarnings decimal(12,4),
   AvgWeeklyEarnings decimal(12,4),
   LocalAvgMonthlyEarnings decimal(12,4),
   AvgMonthlyEarnings decimal(12,4),
   LocalAvgAnnualEarnings decimal(12,4),
   AvgAnnualEarnings decimal(12,4),
   EarningsAttached bool default 0,
   ShiftID int,
   TaskID int,
   InjuryTaskDesc text,
   InjuryExposureID int,
   InjuryExposureDesc text,
   InjurySource1ID int,
   InjurySource2ID int,
   InjurySourceDesc text,
   InjuryObject varchar(128),
   ObjectDesc text,
   RegulatoryRecordable bool default 0,
   PrivacyCase bool default 0,
   Rationale text,
   WorkBegan datetime,
   DateofDeath date,
   InjuryIllnessCategoryID int unsigned not null,
   InjuryIllnessTypeID int unsigned not null,
   PrimaryTreatingFacilityID int,
   EmergencyRoom bool default 0,
   Hospitalized bool default 0,
   RecorderJobTitleID int,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      _RecordID,
      LossInjuryID
   )
) TYPE=InnoDB;
