CREATE TABLE `pple` (
   PersonID int unsigned not null,
   MaritalStatusID int unsigned,
   EmployeeNo varchar(50),
   SocialSecNo varchar(25),
   DriversLicenseNo varchar(25),
   DriversLicenseED varchar(25),
   DriversLicenseSt varchar(25),
   OpsCoVeh bool,
   OpsCommVeh bool,
   MVASigned bool,
   IdentificationNo varchar(128),
   GenderID int unsigned,
   RaceID int unsigned,
   TerminationTypeID int unsigned,
   Active bool,
   EmploymentStatusID int unsigned,
   WageStatusID int unsigned,
   ShiftID int unsigned,
   HourlyWage decimal(12,4),
   Salary decimal(12,4),
   DivisionID int unsigned,
   RegionID int unsigned,
   WorkAvailabilityGroupID int,
   LaborUtilizationRate float,
   I9DocCompleted bool,
   I9ListDocID int unsigned,
   I9ListAID int unsigned,
   I9ListBID int unsigned,
   I9ListCID int unsigned,
   BusinessContinuity bool,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      PersonID
   )
) TYPE=InnoDB;

-- statement separator --


CREATE TABLE `pple_l` (
   _RecordID int unsigned not null auto_increment,
   PersonID int unsigned not null,
   MaritalStatusID int unsigned,
   EmployeeNo varchar(50),
   SocialSecNo varchar(25),
   DriversLicenseNo varchar(25),
   DriversLicenseED varchar(25),
   DriversLicenseSt varchar(25),
   OpsCoVeh bool,
   OpsCommVeh bool,
   MVASigned bool,
   IdentificationNo varchar(128),
   GenderID int unsigned,
   RaceID int unsigned,
   TerminationTypeID int unsigned,
   Active bool,
   EmploymentStatusID int unsigned,
   WageStatusID int unsigned,
   ShiftID int unsigned,
   HourlyWage decimal(12,4),
   Salary decimal(12,4),
   DivisionID int unsigned,
   RegionID int unsigned,
   WorkAvailabilityGroupID int,
   LaborUtilizationRate float,
   I9DocCompleted bool,
   I9ListDocID int unsigned,
   I9ListAID int unsigned,
   I9ListBID int unsigned,
   I9ListCID int unsigned,
   BusinessContinuity bool,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      _RecordID,
      PersonID
   )
) TYPE=InnoDB;
