CREATE TABLE `chm` (
   ChemicalID int unsigned auto_increment not null,
   OrganizationID int,
   ProductName varchar(128),
   CommonName varchar(128),
   ChemicalName varchar(128),
   CASNumber varchar(50),
   ChemicalStatusID int,
   ManufacturerID int,
   MSDSAvailable bool default 0,
   MSDSURL varchar(128),
   RTECSNumber varchar(15),
   RTECSURL varchar(128),
   ICSCNumber varchar(15),
   ICSCURL varchar(128),
   Processed bool default 0,
   TradeSecret bool default 0,
   ExtremelyHazardous bool default 0,
   PotVolatile bool default 0,
   ExceedCoLimits bool default 0,
   ProductIngred bool default 0,
   ContGuarOnFile bool default 0,
   ActiveIngredient varchar(50),
   HealthID int,
   FireID int,
   ReactivityID int,
   SpecialHazardID int,
   SpecialHand text,
   FlashPoint int,
   TempUnitsID int,
   pH int,
   ReportableQuantity int,
   WeightVolUnitsID int,
   FederalWasteID varchar(128),
   Solid bool,
   Liquid bool,
   Gas bool,
   Responsibilitiesdf text,
   Verificationdf text,
   Preparationdf text,
   Applicationdf text,
   PostApplicationdf text,
   Precautionsdf text,
   FirstAiddf text,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      ChemicalID
   )
) TYPE=InnoDB;

-- statement separator --


CREATE TABLE `chm_l` (
   _RecordID int unsigned not null auto_increment,
   ChemicalID int unsigned  not null,
   OrganizationID int,
   ProductName varchar(128),
   CommonName varchar(128),
   ChemicalName varchar(128),
   CASNumber varchar(50),
   ChemicalStatusID int,
   ManufacturerID int,
   MSDSAvailable bool default 0,
   MSDSURL varchar(128),
   RTECSNumber varchar(15),
   RTECSURL varchar(128),
   ICSCNumber varchar(15),
   ICSCURL varchar(128),
   Processed bool default 0,
   TradeSecret bool default 0,
   ExtremelyHazardous bool default 0,
   PotVolatile bool default 0,
   ExceedCoLimits bool default 0,
   ProductIngred bool default 0,
   ContGuarOnFile bool default 0,
   ActiveIngredient varchar(50),
   HealthID int,
   FireID int,
   ReactivityID int,
   SpecialHazardID int,
   SpecialHand text,
   FlashPoint int,
   TempUnitsID int,
   pH int,
   ReportableQuantity int,
   WeightVolUnitsID int,
   FederalWasteID varchar(128),
   Solid bool,
   Liquid bool,
   Gas bool,
   Responsibilitiesdf text,
   Verificationdf text,
   Preparationdf text,
   Applicationdf text,
   PostApplicationdf text,
   Precautionsdf text,
   FirstAiddf text,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      _RecordID,
      ChemicalID
   )
) TYPE=InnoDB;
