CREATE TABLE `lpdps` (
   LossProdServAssnID int unsigned auto_increment not null,
   LossProdServID int unsigned not null,
   ProdServID int unsigned not null,
   MethodofHarm text,
   DefectOriginID int,
   DefectDescription text,
   HazardDescription text,
   SupplierRelated bool default 0,
   TraceNumber varchar(128),
   BatchNumber varchar(128),
   LotNumber varchar(128),
   ModelNumber varchar(128),
   ProductionDate datetime,
   ShippingDate datetime,
   ProductionReviewDate datetime,
   AmountProduced float,
   AmountProducedUnitID int,
   ProductionConclusion text,
   ProcessReviewDate datetime,
   AmountInProcess float,
   AmountInProcessUnitID int,
   ProcessConclusion text,
   ShippingReviewDate datetime,
   AmountShipped float,
   AmountShippedUnitID int,
   ShippingConclusion text,
   InventoryReviewDate datetime,
   AmountinInventory float,
   AmountinInventoryUnitID int,
   InventoryConclusion text,
   ProductAvailable bool default 0,
   PresentDesc text,
   PresentAddress1 varchar(50),
   PresentAddress2 varchar(50),
   PresentCountyID int unsigned,
   PresentCity varchar(50),
   PresentPostalCode varchar(50),
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      LossProdServAssnID
   )
) TYPE=InnoDB;

-- statement separator --


CREATE TABLE `lpdps_l` (
   _RecordID int unsigned not null auto_increment,
   LossProdServAssnID int unsigned  not null,
   LossProdServID int unsigned not null,
   ProdServID int unsigned not null,
   MethodofHarm text,
   DefectOriginID int,
   DefectDescription text,
   HazardDescription text,
   SupplierRelated bool default 0,
   TraceNumber varchar(128),
   BatchNumber varchar(128),
   LotNumber varchar(128),
   ModelNumber varchar(128),
   ProductionDate datetime,
   ShippingDate datetime,
   ProductionReviewDate datetime,
   AmountProduced float,
   AmountProducedUnitID int,
   ProductionConclusion text,
   ProcessReviewDate datetime,
   AmountInProcess float,
   AmountInProcessUnitID int,
   ProcessConclusion text,
   ShippingReviewDate datetime,
   AmountShipped float,
   AmountShippedUnitID int,
   ShippingConclusion text,
   InventoryReviewDate datetime,
   AmountinInventory float,
   AmountinInventoryUnitID int,
   InventoryConclusion text,
   ProductAvailable bool default 0,
   PresentDesc text,
   PresentAddress1 varchar(50),
   PresentAddress2 varchar(50),
   PresentCountyID int unsigned,
   PresentCity varchar(50),
   PresentPostalCode varchar(50),
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      _RecordID,
      LossProdServAssnID
   )
) TYPE=InnoDB;
