CREATE TABLE `chmin` (
   ChemicalInventoryID int unsigned auto_increment not null,
   ChemicalID int,
   OrganizationID int,
   ChemicalStorageMethodID int,
   TrackingNumber varchar(50),
   StorageDesc text,
   ReOrderQuantity float,
   ReOrderQuantityUoMID int,
   StartQuantity float,
   StartQuantityUoMID int,
   Issued float,
   IssuedUoMID int,
   Returned float,
   ReturnedUoMID int,
   Added float,
   AddedUoMID int,
   Transferred float,
   TransferredUoMID int,
   PresentQuantity float,
   PresentQuantityUoMID int,
   PresentQuantityDate date,
   BeginningCalculationDate date,
   EndingCalculationDate date,
   LossQuantity float,
   LossQuantityUoMID int,
   LossCost decimal(12,4),
   MaxAmountAllowed float,
   MaxAmtUoMID int,
   AmountPerYear float,
   AmtPerYrUoMID int,
   AmountPerDay float,
   AmtPerDayUoMID int,
   DaysOnSite float,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      ChemicalInventoryID
   )
) TYPE=InnoDB;

-- statement separator --


CREATE TABLE `chmin_l` (
   _RecordID int unsigned not null auto_increment,
   ChemicalInventoryID int unsigned  not null,
   ChemicalID int,
   OrganizationID int,
   ChemicalStorageMethodID int,
   TrackingNumber varchar(50),
   StorageDesc text,
   ReOrderQuantity float,
   ReOrderQuantityUoMID int,
   StartQuantity float,
   StartQuantityUoMID int,
   Issued float,
   IssuedUoMID int,
   Returned float,
   ReturnedUoMID int,
   Added float,
   AddedUoMID int,
   Transferred float,
   TransferredUoMID int,
   PresentQuantity float,
   PresentQuantityUoMID int,
   PresentQuantityDate date,
   BeginningCalculationDate date,
   EndingCalculationDate date,
   LossQuantity float,
   LossQuantityUoMID int,
   LossCost decimal(12,4),
   MaxAmountAllowed float,
   MaxAmtUoMID int,
   AmountPerYear float,
   AmtPerYrUoMID int,
   AmountPerDay float,
   AmtPerDayUoMID int,
   DaysOnSite float,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      _RecordID,
      ChemicalInventoryID
   )
) TYPE=InnoDB;
