CREATE TABLE `org` (
   OrganizationID int unsigned auto_increment not null,
   ParentOrganizationID int unsigned null,
   DirectionOrganizationID int unsigned null,
   PolicyOrganizationID int unsigned null,
   Name varchar(128),
   ShortName varchar(20),
   Description text,
   IndustryCodeID int unsigned,
   SIC varchar(20),
   OrganizationTypeID int unsigned not null default 0,
   URL varchar(128),
   GuidanceLogoName varchar(50),
   Address1 text,
   CountyID int unsigned,
   City varchar(50),
   PostalCode varchar(50),
   Phone varchar(50),
   Fax varchar(50),
   Email varchar(128),
   RegionID int unsigned,
   DivisionID int unsigned,
   Participant bool,
   Manufacturer bool,
   Contractor bool,
   InsuranceCarrier bool,
   InsuranceBroker bool,
   LawFirm bool,
   GovAgency bool,
   Public bool,
   Customer bool,
   AgencyLevelID int unsigned,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      OrganizationID
   )
) TYPE=InnoDB;

-- statement separator --


CREATE TABLE `org_l` (
   _RecordID int unsigned not null auto_increment,
   OrganizationID int unsigned  not null,
   ParentOrganizationID int unsigned null,
   DirectionOrganizationID int unsigned null,
   PolicyOrganizationID int unsigned null,
   Name varchar(128),
   ShortName varchar(20),
   Description text,
   IndustryCodeID int unsigned,
   SIC varchar(20),
   OrganizationTypeID int unsigned not null default 0,
   URL varchar(128),
   GuidanceLogoName varchar(50),
   Address1 text,
   CountyID int unsigned,
   City varchar(50),
   PostalCode varchar(50),
   Phone varchar(50),
   Fax varchar(50),
   Email varchar(128),
   RegionID int unsigned,
   DivisionID int unsigned,
   Participant bool,
   Manufacturer bool,
   Contractor bool,
   InsuranceCarrier bool,
   InsuranceBroker bool,
   LawFirm bool,
   GovAgency bool,
   Public bool,
   Customer bool,
   AgencyLevelID int unsigned,
   _ModDate datetime not null,
   _ModBy int unsigned not null default 0,
   _Deleted bool not null default 0,
   PRIMARY KEY(
      _RecordID,
      OrganizationID
   )
) TYPE=InnoDB;
